# Generated by Django 5.2.4 on 2025-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoauction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
