# Generated by Django 5.2.4 on 2025-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoauction', '0002_car_description_en_car_description_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
